"""add comfirmation

Revision ID: 51f51de43853
Revises: 2cbf171ffb93
Create Date: 2016-02-01 23:57:13.285123

"""

# revision identifiers, used by Alembic.
revision = '51f51de43853'
down_revision = '2cbf171ffb93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
